global:
  scrape_interval: 15s
# Configuration for scraping metrics from different targets
scrape_configs:
  - job_name: "webmellon-prometheus"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["webmellon-app:3000"] # Use container name
