import { PrismaClient } from "@/lib/generated/prisma/client";

const prisma = new PrismaClient();
const user = await prisma.user.findUnique({
  where: {
    email: "pahnpyotr@gmail.com"
  }
})
const catalogues = {
  "Torrent Sites": [
    { name: "1337x Torrent", url: "https://www.1337x.to/home/" },
    { name: "PirateBay", url: "https://www.pirateproxy-bay.com/" },
    { name: "YTS.MX", url: "https://yts.mx/" },
    { name: "Torrends", url: "https://torrends.to/" },
    { name: "LimeTorrents", url: "https://www.limetorrents.info/" },
    { name: "Rarbg", url: "https://rarbg.to/index80.php" },
    { name: "TorrentDownloads", url: "https://torrentdownloads.unblocknow.cyou/" },
    { name: "Tamil Rockers", url: "https://www.tamilrockermovies.us/" },
    { name: "Tamil Blasters", url: "https://tamilblasters.pm/" },
    { name: "TorrentLite", url: "https://torrentlite.org" }
  ],
  "Streaming": [
    { name: "Vumoo", url: "https://vumoo.to/" },
    { name: "WatchMovie", url: "https://ww3.watchmovie.movie/" },
    { name: "123Moviess", url: "https://www3.123moviess.net/" },
    { name: "123Movies", url: "https://wvw1.123movies.net/" },
    { name: "Youtube", url: "https://youtube.com/" },
    { name: "Odysee", url: "https://odysee.com/" },
    { name: "Documentary Heaven", url: "https://documentaryheaven.com/" },
    { name: "PeerTube", url: "https://peer.tube" },
    { name: "Actvid.com", url: "https://www.actvid.com" },
    { name: "YouTube Movies", url: "https://www.youtube.com/movies" },
    { name: "YouTube Music", url: "https://music.youtube.com/" },
    { name: "Twitch", url: "https://www.twitch.tv/" },
    { name: "Spotify", url: "https://open.spotify.com/" },
    { name: "BBC-iplayer", url: "https://www.bbc.co.uk/iplayer" },
    { name: "SoundCloud", url: "https://soundcloud.com/" },
    { name: "Channel4", url: "https://www.channel4.com/" },
    { name: "France Tv", url: "https://www.france.tv/" },
    { name: "Comedy Central", url: "https://www.cc.com/" },
    { name: "ARTE", url: "https://www.arte.tv/en/" },
    { name: "Anime Planet", url: "https://www.anime-planet.com/" },
    { name: "Aniwave", url: "https://aniwave.to" },
    { name: "DGT", url: "https://deepgoretube.site/" },
    { name: "Russia.tv", url: "https://smotrim.ru/" },
    { name: "Manga Reader", url: "https://mangareader.to/" },
    { name: "Russian Film Hub", url: "https://russianfilmhub.com/" },
    { name: "CricHD", url: "https://www.crichd.live/home27" },
    { name: "Jio Cinema", url: "https://www.jiocinema.com/" },
    { name: "Tamil Yogi", url: "https://tamilyogi.to/home/" },
    { name: "PopcornFlix", url: "https://www.popcornflix.com/#/home" },
    { name: "Einthusan", url: "https://einthusan.tv/intro/" },
    { name: "MovieWebApp", url: "https://movie-web.app/search/movie" },
    { name: "HiMovies", url: "https://himovies.sx/home" },
    { name: "EV01", url: "https://ev01.cc" },
    { name: "Fmovies", url: "https://fmovies.gift" },
    { name: "Maoists on PeerTube", url: "https://peertube.it/c/maoists/videos" },
    { name: "I have no TV", url: "https://ihavenotv.com" },
    { name: "alphatron", url: "https://alphatron.tv" },
  ],
  "Aides": [
    { name: "W3Schools", url: "https://www.w3schools.com/" },
    { name: "Learn X in Y minutes", url: "https://learnxinyminutes.com/" },
    { name: "Wikipedia", url: "https://www.wikipedia.org/" },
    { name: "FreeCode Camp", url: "https://www.freecodecamp.org/" },
    { name: "JavaTPoint", url: "https://www.javatpoint.com/" },
    { name: "Kali Training", url: "https://kali.training/" },
    { name: "Ted", url: "https://www.ted.com/" },
    { name: "Luke Smith's Webpage", url: "https://lukesmith.xyz/" },
    { name: "ArchWiki", url: "https://wiki.archlinux.org/" },
    { name: "GentooWiki", url: "https://wiki.gentoo.org/wiki/Main_Page" },
    { name: "Wiki-How", url: "https://www.wikihow.com/Main-Page" },
    { name: "Math Blog", url: "https://mathblog.com/" },
    { name: "Centre of Policy Research", url: "https://www.cprindia.org/" },
    { name: "Seminars Only", url: "https://www.seminarsonly.com/" },
    { name: "NCERT", url: "https://ncert.nic.in/" },
    { name: "Sabine Hossenfelder", url: "https://backreaction.blogspot.com/?m=1" },
    { name: "Britannica", url: "https://www.britannica.com/" },
    { name: "Brilliant.org", url: "https://brilliant.org/" },
    { name: "The Great Courses Daily", url: "https://www.thegreatcoursesdaily.com/" },
    { name: "Sololearn", url: "https://www.sololearn.com/home" },
    { name: "Duolingo", url: "https://www.duolingo.com/" },
    { name: "Khan Academy", url: "https://www.khanacademy.org/" },
    { name: "WolframAlpha", url: "https://www.wolframalpha.com/" },
    { name: "Code With Harry", url: "https://www.codewithharry.com/" },
    { name: "EngVid", url: "https://www.engvid.com/" },
    { name: "The Cyber Mentor", url: "https://www.thecybermentor.com/" },
    { name: "System Crafters", url: "https://systemcrafters.net/" },
    { name: "Learn Insta", url: "https://www.learninsta.com/" },
    { name: "School For Material Research", url: "https://www.schoolformaterialistresearch.org/" },
    { name: "TinkerCad", url: "https://www.tinkercad.com/" },
    { name: "Android.Develpers", url: "https://developer.android.com/" },
    { name: "Electroboom", url: "https://www.electroboom.com/" },
    { name: "Distro.Tube", url: "https://distro.tube/index.html" },
    { name: "Career India", url: "https://www.careerindia.com/" },
    { name: "Exercism", url: "https://exercism.org/" },
    { name: "Math10.com", url: "https://www.math10.com/" },
    { name: "Intel Jupyter DevCloud", url: "https://notebooks.edge.devcloud.intel.com/user/u191766/lab" },
    { name: "OmniGlot", url: "https://www.omniglot.com/index.htm" },
    { name: "Trendlyne", url: "https://trendlyne.com/markets-today-loggedin/" },
    { name: "AICT", url: "https://www.aict.info/?csc=2024" },
    { name: "Stable Diffusion", url: "https://stablediffusionweb.com" },
    { name: "Open Source Front Ends to Social Media", url: "https://github.com/mendel5/alternative-front-ends" },
    { name: "Working Servers", url: "https://farside.link" },
    { name: "youtubevanced", url: "https://youtubevanced.org" },
    { name: "fontspace", url: "https://www.fontspace.com" },
    { name: "Da Font", url: "https://www.dafont.com" },
    { name: "TypeType", url: "https://typetype.org/freefonts/" },
    { name: "Google Fonts", url: "https://fonts.google.com" },
    { name: "awesome-oss-alternatives", url: "https://github.com/RunaCapital/awesome-oss-alternatives" },
    { name: "Valeriy Shevchenko", url: "https://krevetk0.medium.com" }
  ],
  "Journals": [
    { name: "ScienceX", url: "https://sciencex.com/" },
    { name: "Phys.org", url: "https://phys.org/" },
    { name: "Medical Express", url: "https://medicalxpress.com/" },
    { name: "TechExplore", url: "https://techxplore.com/" },
    { name: "MedCircle", url: "https://medcircle.com/" },
    { name: "Scientific American", url: "https://www.scientificamerican.com/" },
    { name: "Nature", url: "https://www.nature.com/nature/articles" },
    { name: "NobelPrize", url: "https://www.nobelprize.org/" },
    { name: "BreakthroughPrize", url: "https://breakthroughprize.org/" },
    { name: "AbelPrize", url: "https://www.abelprize.no/" },
    { name: "National Geographic", url: "https://www.nationalgeographic.com/" },
    { name: "History", url: "https://www.history.com/" },
    { name: "Royal Society", url: "https://royalsociety.org/" },
    { name: "Academia", url: "https://www.academia.edu/" },
    { name: "Quickonomics", url: "https://quickonomics.com/" },
    { name: "PubChem", url: "https://pubchem.ncbi.nlm.nih.gov/" },
    { name: "NCBI", url: "https://www.ncbi.nlm.nih.gov/" },
    { name: "Department of Science and Technology", url: "https://dst.gov.in/" },
    { name: "Clinical Trials", url: "https://clinicaltrials.gov/" },
    { name: "Science.Gov", url: "https://www.science.gov/" },
    { name: "AAAS", url: "https://www.aaas.org/journals" },
    { name: "Google-Scholar", url: "https://scholar.google.com/" },
    { name: "Caltech Library", url: "https://www.library.caltech.edu/" },
    { name: "Oxford Library", url: "https://www.ox.ac.uk/research/libraries" },
    { name: "Cambridge University", url: "https://www.lib.cam.ac.uk/" },
    { name: "Harvard Library", url: "https://library.harvard.edu/" },
    { name: "QuantaMagazine", url: "https://www.quantamagazine.org/" },
    { name: "Wired Magazine", url: "https://www.wired.com/" },
    { name: "Seeker", url: "https://www.seeker.com/" },
    { name: "Chem Libretexts", url: "https://chem.libretexts.org/" },
    { name: "Science Direct", url: "https://www.sciencedirect.com/" },
    { name: "AstroGeeksz", url: "https://astrogeekzco.com/" },
    { name: "Tech Crunch", url: "https://techcrunch.com/" },
    { name: "Dr.Baird Answers", url: "https://www.wtamu.edu/~cbaird/sq/index.html" },
    { name: "Fermilab", url: "https://www.fnal.gov/" },
    { name: "Frontiers", url: "https://www.frontiersin.org/" },
    { name: "Clark University", url: "https://www.clarku.edu/" }
  ],
  "Arts": [
    { name: "Poetry Foundation", url: "https://www.poetryfoundation.org/" },
    { name: "Pinterest", url: "https://www.pinterest.com/" },
    { name: "Rekhta", url: "https://www.rekhta.org/" },
    { name: "Hindwi", url: "https://www.hindwi.org/" },
    { name: "ArtNet", url: "http://www.artnet.com/" },
    { name: "Varavara Rao", url: "https://web.archive.org/web/20160313105811/http://varavararao.org/" },
    { name: "Poetry International", url: "https://www.poetryinternational.com/en/" },
    { name: "Socialist Stories", url: "http://www.socialiststories.com/en/" },
    { name: "Modern Poetry In Translation", url: "https://modernpoetryintranslation.com" },
    { name: "Upscale", url: "https://www.upscale.media" }
  ],
  "FLOSS": [
    { name: "GitHub", url: "https://github.com/" },
    { name: "TOR", url: "https://www.torproject.org/" },
    { name: "QuteBrowser", url: "https://qutebrowser.org/doc/help/" },
    { name: "Arch User Repository", url: "https://aur.archlinux.org/" },
    { name: "GitLab", url: "https://about.gitlab.com" },
    { name: "Suckless", url: "https://suckless.org" },
    { name: "GNU", url: "https://www.gnu.org/home.en.html" },
    { name: "FreeBSD", url: "https://docs.freebsd.org/en/" },
    { name: "Stallman's Site", url: "https://stallman.org/" },
    { name: "Temp-Mail", url: "https://temp-mail.org" },
    { name: "ACM SRG", url: "https://garvjain.notion.site/ACM-SRG-acfc9dd09a4146b9960eeedde80a8ae3" },
    { name: "CP-algorithms", url: "https://cp-algorithms.com" }
  ],
  "Libraries": [
    { name: "The Anarchist Library", url: "http://theanarchistlibrary.org/special/index" },
    { name: "ZlibWorking", url: "https://z-library.rs" },
    { name: "Delphi Classics", url: "https://www.delphiclassics.com/" },
    { name: "Internet Archive", url: "https://archive.org/" },
    { name: "NCERT Books", url: "https://ncert.nic.in/textbook.php" },
    { name: "Lawrence Wishart", url: "https://lwbooks.co.uk/" },
    { name: "Sci-Hub", url: "https://sci-hub.do/" },
    { name: "PDF drive", url: "https://www.pdfdrive.com/" },
    { name: "Indian Memory Project", url: "https://www.indianmemoryproject.com/" },
    { name: "NDLI", url: "https://ndl.iitkgp.ac.in/" },
    { name: "ASI", url: "https://asi.nic.in/" },
    { name: "Paul's Online Notes", url: "https://tutorial.math.lamar.edu/" },
    { name: "archive.today", url: "https://archive.ph/" },
    { name: "LibriVox", url: "https://librivox.org/" },
    { name: "Emerald", url: "https://www.emerald.com/insight/" },
    { name: "Libgen", url: "https://libgen.gs/" },
    { name: "Foreign Languages Press", url: "https://foreignlanguages.press/" },
    { name: "Academic Torrents", url: "https://academictorrents.com/" },
    { name: "Docslib", url: "https://docslib.org/" },
    { name: "Annas Archive", url: "https://annas-archive.org/" },
    { name: "Ocean of Pdf", url: "https://oceanofpdf.com" },
    { name: "openstax", url: "https://openstax.org" },
    { name: "Creative Computing", url: "https://hybrid.concordia.ca/jdesplan/online_schedule.html" },
    { name: "UIverse", url: "https://uiverse.io" }
  ],
  "Dictionaries": [
    { name: "Google.Translate", url: "https://translate.google.com/" },
    { name: "UrbanDictionary", url: "https://www.urbandictionary.com/" },
    { name: "Merriam-Webster", url: "https://www.merriam-webster.com/" },
    { name: "WebMD", url: "https://www.webmd.com/default.htm" },
    { name: "Linguee/DeepL", url: "https://www.linguee.com/" },
    { name: "Internet Encyclopedia of Philosophy", url: "https://iep.utm.edu" }
  ],
  "News Sites": [
    { name: "DeustcheWelle", url: "https://www.dw.com/" },
    { name: "Al Jazeera", url: "https://aljazeera.com/" },
    { name: "Bloomberg", url: "https://www.bloomberg.com/" },
    { name: "NDTV", url: "https://www.ndtv.com/" },
    { name: "Indian Express", url: "https://indianexpress.com/" },
    { name: "The Hindu", url: "https://www.thehindu.com/" },
    { name: "The Times Of India", url: "https://timesofindia.indiatimes.com/" },
    { name: "The Economist", url: "https://economist.com/" },
    { name: "Politico", url: "https://www.politico.com/" },
    { name: "BBC", url: "https://www.bbc.com/" },
    { name: "Forbes", url: "https://www.forbes.com/" },
    { name: "AssociatedPress", url: "https://apnews.com/" },
    { name: "SCMP", url: "https://www.scmp.com/" },
    { name: "Russia News Now", url: "https://therussophile.org/" },
    { name: "ED Times", url: "https://edtimes.in/" },
    { name: "RT", url: "https://www.rt.com/" },
    { name: "The Moscow Times", url: "https://www.themoscowtimes.com/" },
    { name: "NPR", url: "https://www.npr.org/" },
    { name: "AfricaNews", url: "https://www.africanews.com/" },
    { name: "Worldpress", url: "https://www.worldpress.org/" },
    { name: "Asia Times", url: "https://asiatimes.com/" },
    { name: "Nikkei Asia", url: "https://asia.nikkei.com/" },
    { name: "The Kashmir Scenario", url: "https://thekashmirscenario.com/" },
    { name: "The Kashmir Observer", url: "https://kashmirobserver.net/" },
    { name: "LatinAmerican Post", url: "https://latinamericanpost.com/" },
    { name: "France24", url: "https://www.france24.com/" },
    { name: "The Nation", url: "https://www.thenation.com/" },
    { name: "Pakistan Today", url: "https://www.pakistantoday.com.pk/" },
    { name: "United Nations", url: "https://www.un.org/en" },
    { name: "The International News", url: "https://www.thenews.com.pk/" },
    { name: "The Rand", url: "https://www.rand.org/" },
    { name: "The Swaddle", url: "https://theswaddle.com/" },
    { name: "The Diplomat", url: "https://thediplomat.com/" },
    { name: "CNN", url: "https://www.cnn.com/" },
    { name: "PTI News", url: "https://ptinews.com/" },
    { name: "Reuters", url: "https://www.reuters.com/" },
    { name: "TheGrayZone", url: "https://thegrayzone.com/" },
    { name: "DemocracyNow", url: "https://www.democracynow.org/" },
    { name: "TheIntercept", url: "https://theintercept.com/" },
    { name: "BloombergQuint", url: "https://www.bloombergquint.com/" },
    { name: "TheQuint", url: "https://www.thequint.com/" },
    { name: "CaravanMagazine", url: "https://caravanmagazine.in/" },
    { name: "ThePrint", url: "https://theprint.in/" },
    { name: "TheConversation", url: "https://theconversation.com/au" },
    { name: "British Pathe", url: "https://www.britishpathe.com/" },
    { name: "Le Monde", url: "https://www.lemonde.fr" },
    { name: "Global Times", url: "https://www.globaltimes.cn/index.html" },
    { name: "Observer Research Foundation", url: "https://www.orfonline.org/" },
    { name: "The Tribune India", url: "https://www.tribuneindia.com/" },
    { name: "EastMojo", url: "https://www.eastmojo.com/" },
    { name: "Scroll", url: "https://scroll.in/" },
    { name: "Deccan Chronicle", url: "https://www.deccanchronicle.com/south" },
    { name: "South Asian Daily", url: "http://southasiandaily.com/" },
    { name: "National Herald", url: "https://www.nationalheraldindia.com/" },
    { name: "Alt News", url: "https://www.altnews.in/" },
    { name: "Empire Files", url: "http://theempirefiles.tv/" },
    { name: "The Statesman", url: "https://www.thestatesman.com/" },
    { name: "Indian Defence Review", url: "http://www.indiandefencereview.com/" },
    { name: "Lok Sabha Tv", url: "https://loksabhatv.nic.in/" },
    { name: "Rajya Sabha Tv", url: "https://rstv.nic.in/" },
    { name: "Open Democracy", url: "https://www.opendemocracy.net/en/" },
    { name: "Military Embedded Systems", url: "https://militaryembedded.com/" },
    { name: "Investor's Business Daily", url: "https://www.investors.com/" },
    { name: "Multipolarista", url: "https://multipolarista.com/" },
    { name: "South Asia Terrorism Portal", url: "https://www.satp.org/" },
    { name: "Article 14", url: "https://article-14.com" },
    { name: "Outlook India", url: "https://www.outlookindia.com" },
    { name: "The Established", url: "https://www.theestablished.com" }
  ],
  "Intel Sources": [
    { name: "Legislative Department of India", url: "https://legislative.gov.in/" },
    { name: "Gov Data In", url: "https://data.gov.in/" },
    { name: "Ministry of Law & Justice", url: "https://lawmin.gov.in/" },
    { name: "National Portal of India", url: "https://www.india.gov.in/" },
    { name: "Constitute Project", url: "https://constituteproject.org" },
    { name: "Centre of Policy Research", url: "https://www.cprindia.org/" },
    { name: "Niti Aayog", url: "http://niti.gov.in/" },
    { name: "SATP", url: "https://www.satp.org/about-satp" },
    { name: "Wikileaks", url: "https://wikileaks.org/" },
    { name: "BannedThought.Net", url: "http://www.bannedthought.net/" },
    { name: "ICIJ", url: "https://www.icij.org/" }
  ],
  "Red Materials": [
    { name: "Paul Cockshott", url: "https://paulcockshott.wordpress.com/" },
    { name: "David Harvey", url: "http://davidharvey.org/" },
    { name: "OIC", url: "https://oicmundo.wordpress.com/" },
    { name: "In Defence of Marxism", url: "https://www.marxist.com/" },
    { name: "Marxists Internet Archive", url: "https://www.marxists.org/" },
    { name: "Midwestern Marx", url: "https://www.midwesternmarx.com/" },
    { name: "Libcom", url: "https://libcom.org/" },
    { name: "Jacobin Magazine", url: "https://www.jacobinmag.com/" },
    { name: "TheWire", url: "https://thewire.in/" },
    { name: "PWG-Statements", url: "http://209.151.22.101/India/CPI-Maoist-Docs/index.htm" },
    { name: "It's Going Down", url: "https://itsgoingdown.org" },
    { name: "Anarchism.Net", url: "https://anarchism.net/sitemap.htm" },
    { name: "AntiFascistNetwork", url: "https://antifascistnetwork.org/" },
    { name: "ML Theory", url: "https://mltheory.wordpress.com/" },
    { name: "Socialism101", url: "https://www.socialism101.com/" },
    { name: "Laal Band", url: "https://laal.band/" },
    { name: "Communist International", url: "https://ci-ic.org/" },
    { name: "RedSpark", url: "https://www.redspark.nu/en/" },
    { name: "Dem Volke Dienen", url: "https://www.demvolkedienen.org/index.php/en/" },
    { name: "Struggle-Sessions", url: "https://struggle-sessions.com/" },
    { name: "Red Sun Magazine", url: "http://www.redsun.org/" },
    { name: "TheMorningStar", url: "https://www.morningstaronline.co.uk/" },
    { name: "People's Dispatch", url: "http://peoplesdispatch.org/" },
    { name: "Qiao Collective", url: "https://www.qiaocollective.com/" },
    { name: "Espresso Stalinist", url: "https://espressostalinist.com/" },
    { name: "Black Agenda Report", url: "https://www.blackagendareport.com/" },
    { name: "History is a Weapon", url: "http://hiaw.org/" },
    { name: "Jamhoor", url: "https://www.jamhoor.org/" },
    { name: "Progressive International", url: "https://progressive.international/" },
    { name: "People's Bayonet", url: "https://peoplesbayo.net/" },
    { name: "The Red Flag", url: "https://the-red-flag.org/" },
    { name: "Revolutionary Democracy Journal", url: "https://www.revolutionarydemocracy.org/" },
    { name: "Caleb Maupin", url: "https://calebmaupin.com/" },
    { name: "Redpolemique Wordpress", url: "https://redpolemique.wordpress.com/" },
    { name: "Massline.org", url: "https://www.massline.org/" },
    { name: "Anti-Dialectics", url: "http://www.anti-dialectics.co.uk/" },
    { name: "Communist Ghadar Party of India", url: "http://cgpi.org/category/language/en" },
    { name: "ProleWiki", url: "https://en.prolewiki.org/wiki/ProleWiki:Main_page" },
    { name: "RedFish", url: "https://redfish.media/" },
    { name: "Soviet History", url: "https://soviethistory.msu.edu/" },
    { name: "Anti-Imperialism.org", url: "http://antiimperialism.org" },
    { name: "PRWC Newsroom", url: "https://prwcinfo.wordpress.com/" },
    { name: "Counter Currents.Org", url: "https://countercurrents.org/" },
    { name: "Revolution in South Asia", url: "https://southasiarev.wordpress.com/" },
    { name: "ICSPWI", url: "https://icspwindia.wordpress.com/" },
    { name: "Janapati", url: "https://www.janapati.net/" },
    { name: "TKP-ML", url: "https://www.tkpml.com/en/" },
    { name: "Tribune Of the People", url: "https://tribuneofthepeoplenews.wordpress.com/" },
    { name: "Rupe India", url: "https://www.rupe-india.org/" },
    { name: "Feminism In India", url: "https://feminisminindia.com/" },
    { name: "Feminist Law Archives", url: "https://feministlawarchives.pldindia.org/" },
    { name: "Indian Cultural Forum", url: "https://indianculturalforum.in/" },
    { name: "Philippine Revolution", url: "https://philippinerevolution.nu/" },
    { name: "MaoistRoadBlogSpot", url: "https://maoistroad.blogspot.com/" },
    { name: "Revolutionary Students' Front", url: "https://eimuhurtersf.wordpress.com/" },
    { name: "Towards a New Dawn", url: "https://toanewdawn.in/" },
    { name: "Daziba Rojo", url: "https://dazibaorojo08.blogspot.com/" },
    { name: "Shola Jawid", url: "http://www.sholajawid.org/update/index_english.html" },
    { name: "Communist (Maoist) Party of Afghanistan", url: "https://cmpa.io/en/" },
    { name: "The New Wave", url: "https://new-wave-nw.blogspot.com/" },
    { name: "Worker Socialist", url: "https://workersocialist.blogspot.in/" },
    { name: "Red Library", url: "https://redlibrary.xyz/" },
    { name: "Jose Maria Sison", url: "https://www.josemariasison.eu/" },
    { name: "Tjen Folket", url: "https://tjen-folket.no/index.php/en/" },
    { name: "Read Marx Everyday", url: "http://www.readmarxeveryday.org/" },
    { name: "The Naxalbari Blogpost", url: "https://thenaxalbari.blogspot.com/" },
    { name: "Nazariya Magazine", url: "https://nazariyamagazine.in" },
    { name: "Kevin Rashid Jones", url: "https://rashidmod.com" },
    { name: "BlackFlagIndia", url: "https://blackflagindia.com/" },
    { name: "Ronoturjo.ML", url: "https://www.ronoturjo.ml/" },
    { name: "Red Stockings", url: "https://www.redstockings.org" },
    { name: "Radical Notes", url: "https://radicalnotes.org" },
    { name: "Peoples' Struggle", url: "https://peoplesstruggle.org/en/" },
    { name: "Red Thought Mag", url: "https://redthoughtmag.wordpress.com" },
    { name: "The Masses", url: "https://the-masses.org" },
    { name: "Ajith's Page", url: "https://ajithspage.in/wp/" },
    { name: "Mehnat Kash", url: "https://mehnatkash.in" },
    { name: "Youth Ki Awaz", url: "https://www.youthkiawaaz.com/latest-posts/" },
    { name: "Reporter's Collective", url: "https://www.reporters-collective.in" },
    { name: "Baru Satwarag", url: "https://barusatwarag.wordpress.com" },
    { name: "Kosambi Circle", url: "https://www.kosambicircle.com" },
    { name: "Monthly Review", url: "https://monthlyreview.org" },
    { name: "Himal Mag", url: "https://www.himalmag.com" },
    { name: "The Red Flag (EN)", url: "https://the-red-flag.org/en" },
    { name: "Communist Party of Peru", url: "https://gplpcp.wordpress.com" },
    { name: "Radical Polemic", url: "https://radicalpolemic.wordpress.com" },
    { name: "Idees Nouvelles Idees Proletariennes", url: "https://koleksyon-inip.org" },
    { name: "Materialisme Dialectique", url: "https://materialisme-dialectique.com" },
    { name: "Kractivism", url: "https://www.kractivist.org" },
    { name: "Lal Salaam", url: "https://lalsalaam.wordpress.com" },
    { name: "The Red Herald", url: "https://redherald.org" },
    { name: "Material Journal", url: "https://materialjournal.net" },
    { name: "Indian Vanguard", url: "https://indianvanguard.wordpress.com/" },
    { name: "Anti Imperialist Camp", url: "https://www.antiimperialista.org/en" },
    { name: "Sanhati", url: "https://sanhati.com" },
    { name: "Senkanal", url: "https://senkanal.com" },
    { name: "Vinavu", url: "https://www.vinavu.com" },
    { name: "kites-journal", url: "https://kites-journal.org" },
    { name: "RSF journal", url: "https://chhatrafauj.wordpress.com" },
    { name: "FACAM", url: "https://facam.org" },
    { name: "New Left Review", url: "https://newleftreview.org" },
    { name: "Kanal Books", url: "https://kanalbooks.blogspot.com" },
    { name: "Unity Struggle Unity", url: "https://unity-struggle-unity.org/?utm_source=search.brave.com&referrer-analytics=1" },
    { name: "Anvil Mag", url: "https://anvilmag.in" },
    { name: "CHunqiao Pub", url: "https://chunqiao.pub" },
    { name: "Maoist Communist Union", url: "https://maoistcommunistunion.com" },
    { name: "Counter View", url: "https://www.counterview.net" },
    { name: "NODO50", url: "https://info.nodo50.org" },
    { name: "The Worker", url: "https://theworker.news" }
  ]
}

async function main() {
  // Assuming 'catalogues' is an object where the key is the catalogue name and value is an array of websites
  for (const [catalogueName, sites] of Object.entries(catalogues)) {
    // Upsert Catalogue (create or update if it already exists for the user)
    const catalogue = await prisma.catalogue.upsert({
      where: {
        user_catalogue_name_unique: {
          name: catalogueName,
          userId: user?.id ?? "",  // Ensure we're looking for the catalogue belonging to the current user
        },
      },
      update: {},
      create: {
        name: catalogueName,
        userId: user?.id ?? "",
      },
    })

    // Upsert Websites for this catalogue
    for (const site of sites) {
      await prisma.website.upsert({
        where: {
          user_website_name_unique: {
            name: site.name,
            userId: user?.id ?? "",  // Ensure we're looking for the website belonging to the current user
          },
        },
        update: {},
        create: {
          name: site.name,
          userId: user?.id ?? "",
          url: site.url,
          favicon: `https://www.google.com/s2/favicons?sz=64&domain=${new URL(site.url).hostname}`,
          catalogueId: catalogue.id,
        },
      })
    }
  }
  console.log('✅ All websites seeded by category.')
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
